"""
Django settings for barokah project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
# Contoh: Tambahkan import ini di bagian atas file Anda, setelah 'import os'
from celery.schedules import crontab 

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-djow__!qejr_$v@1oox3e+4*1_-vzvuyahx56_db17t=pe3qs7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'barokah.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'barokah.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'id-id'

TIME_ZONE = 'Asia/Makassar'

USE_I18N = True

USE_TZ = True

# Jazzmin Settings
JAZZMIN_SETTINGS = {
    "site_title": "Barokah Admin",
    "site_header": "Barokah Admin",
    "site_brand": "UD. Barokah Jaya Beton",
    "site_icon": "images/favicon.png",
    "welcome_sign": "Selamat Datang di Dashboard Admin Barokah",
    "copyright": "Barokah Beton",
    "search_model": "core.Pelanggan",
    "user_avatar": None,
    "topmenu_links": [],
    "usermenu_links": [
        {"name": "Profile", "url": "admin:core_pelanggan_change", "icon": "fas fa-user-circle"},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": ["auth.user", "auth.group"],
    "order_with_respect_to": ["core", "core.Pelanggan", "core.Kategori", "core.Produk", "core.Transaksi", "core.DiskonPelanggan", "core.Notifikasi"],
    "custom_links": {},
    "icons": {
        "core.Pelanggan": "fas fa-users",
        "core.Produk": "fas fa-box-open",
        "core.Transaksi": "fas fa-shopping-cart",
        "core.DetailTransaksi": "fas fa-receipt",
        "core.Kategori": "fas fa-tags",
        "core.Notifikasi": "fas fa-bell",
        "core.DiskonPelanggan": "fas fa-percent",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": False,
    "custom_css": None,
    "custom_js": None,
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {"core.Pelanggan": "collapsible", "core.Transaksi": "single"},
    "theme": "united",
    "dashboard_title": "Dashboard",
    "sidebar": "sidebar-light-info",
    "navbar": "navbar-white navbar-light",
    "footer": "footer-dark",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

JAZZMIN_UI_TWEAKS = {
    "theme": "united",
    "dark_mode_theme": None,
    "sidebar": "sidebar-light-info",
    "navbar": "navbar-white navbar-light",
    "footer": "footer-dark",
}

# Custom template directory
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'core', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'




# ... (Kode setting Django lainnya seperti BASE_DIR, SECRET_KEY, DEBUG, ALLOWED_HOSTS, dst.)
# ...

# --------------------------------------------------------------------------
# CELERY CONFIGURATION (menggunakan Redis sebagai Message Broker)
# --------------------------------------------------------------------------
# BROKER_URL adalah alamat ke Redis. Port default Redis adalah 6379.
# Anda perlu menjalankan Redis Server secara lokal agar ini berfungsi.
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0' 

# Backend digunakan untuk menyimpan hasil tasks (opsional, tetapi direkomendasikan).
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/0'

CELERY_TIMEZONE = "Asia/Makassar" 

# 🚨 TAMBAHAN: Celery Beat Settings (Untuk Tugas Terjadwal)
CELERY_BEAT_SCHEDULE = {
    # TUGAS 1: Cek Deadline Pembayaran (Berjalan setiap 5 menit)
    'check-payment-deadlines-every-5-minutes': {
        'task': 'core.tasks.check_payment_deadlines',
        'schedule': 300.0, # 300 detik = 5 menit
        'args': (),
        'options': {'queue': 'celery'}
    },
    # TUGAS 2: Kirim Ucapan Ulang Tahun (Berjalan Setiap Hari jam 8 pagi)
    'send-daily-birthday-greetings': {
        'task': 'core.tasks.send_birthday_greetings',
        # crontab(minute, hour, ...) -> Setiap hari pada pukul 08:00
        'schedule': crontab(hour=8, minute=0), 
        'args': (),
        'options': {'queue': 'celery'}
    },
    # TUGAS 3: Menonaktifkan Diskon Ulang Tahun (Berjalan Setiap Awal Jam)
    'disable-expired-birthday-discounts': {
        'task': 'core.tasks.disable_birthday_discounts',
        # crontab(minute=0) -> Setiap jam pada menit ke-0 (misal 09:00, 10:00)
        'schedule': crontab(minute=0), 
        'args': (),
        'options': {'queue': 'celery'}
    },
    # TUGAS 4: Pengingat Pra-Jatuh Tempo Pembayaran (Berjalan setiap 1 jam)
    'check-and-send-payment-reminder-every-hour': {
        'task': 'core.tasks.check_and_send_payment_reminder',
        'schedule': crontab(minute='0', hour='*'),
        'args': (),
        'options': {'queue': 'celery'}
    },
    # TUGAS 5: Laporan Stok Rendah ke Admin (Setiap hari pukul 09:00)
    'check-for-low-stock-daily-9am': {
        'task': 'core.tasks.check_for_low_stock',
        'schedule': crontab(hour=9, minute=0),
        'args': (),
        'options': {'queue': 'celery'}
    },
}
# 🚨 AKHIR TAMBAHAN

# --------------------------------------------------------------------------
# DJANGO EMAIL CONFIGURATION (Produksi - Menggunakan SMTP GMAIL)
# --------------------------------------------------------------------------
# Menggunakan SMTP Backend agar email dikirim sungguhan melalui server Gmail
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# Konfigurasi Server Gmail
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True # Penting untuk koneksi aman

# 🚨 GANTI DENGAN KREDENSIAL ASLI ANDA
# 1. EMAIL_HOST_USER: Masukkan alamat email Gmail Anda yang sebenarnya
EMAIL_HOST_USER = 'setia170104@gmail.com' 
# 2. EMAIL_HOST_PASSWORD: Masukkan APP PASSWORD 16 digit yang Anda buat (Lihat panduan di bawah)
EMAIL_HOST_PASSWORD = 'xtia wsxi gfbw zdgf' # <--- HARUS DIGANTI!

# Email yang akan muncul di kolom 'From' (Email Pengirim Default)
DEFAULT_FROM_EMAIL = 'setia170104@gmail.com' 
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# ... (Kode setting Django lainnya seperti STATIC_URL, TEMPLATES, WSGI_APPLICATION, dst.)