# Generated by Django 4.2 on 2025-11-20 16:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama_kategori', models.CharField(max_length=255, verbose_name='Nama Kategori')),
            ],
            options={
                'verbose_name_plural': 'Kategori',
                'db_table': 'kategori',
            },
        ),
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama_pelanggan', models.CharField(max_length=255, verbose_name='Nama Pelanggan')),
                ('alamat', models.TextField(verbose_name='Alamat')),
                ('tanggal_lahir', models.DateField(verbose_name='Tanggal Lahir')),
                ('no_hp', models.CharField(max_length=20, verbose_name='Nomor HP')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=128, verbose_name='Password')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Pelanggan',
                'db_table': 'pelanggan',
            },
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal', models.DateTimeField(default=datetime.date.today)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total')),
                ('ongkir', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ongkos Kirim')),
                ('status_transaksi', models.CharField(choices=[('DIPROSES', 'Diproses'), ('DIBAYAR', 'Dibayar'), ('DIKIRIM', 'Dikirim'), ('SELESAI', 'Selesai'), ('DIBATALKAN', 'Dibatalkan')], default='DIPROSES', max_length=50, verbose_name='Status Transaksi')),
                ('bukti_bayar', models.FileField(blank=True, null=True, upload_to='bukti_pembayaran/', verbose_name='Bukti Pembayaran')),
                ('alamat_pengiriman', models.TextField(blank=True, null=True, verbose_name='Alamat Pengiriman')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Feedback')),
                ('fotofeedback', models.ImageField(blank=True, null=True, upload_to='feedback_images/', verbose_name='Foto Feedback')),
                ('waktu_checkout', models.DateTimeField(blank=True, null=True)),
                ('batas_waktu_bayar', models.DateTimeField(blank=True, null=True)),
                ('idPelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pelanggan', verbose_name='Pelanggan')),
            ],
            options={
                'verbose_name_plural': 'Transaksi',
                'db_table': 'transaksi',
            },
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama_produk', models.CharField(max_length=255, verbose_name='Nama Produk')),
                ('deskripsi_produk', models.TextField(verbose_name='Deskripsi Produk')),
                ('foto_produk', models.ImageField(upload_to='produk_images/', verbose_name='Foto Produk')),
                ('stok_produk', models.IntegerField(verbose_name='Stok Produk')),
                ('harga_produk', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Harga Produk')),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.kategori', verbose_name='Kategori')),
            ],
            options={
                'verbose_name_plural': 'Produk',
                'db_table': 'produk',
            },
        ),
        migrations.CreateModel(
            name='Notifikasi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipe_pesan', models.CharField(max_length=50, verbose_name='Tipe Pesan')),
                ('isi_pesan', models.TextField(verbose_name='Isi Pesan')),
                ('is_read', models.BooleanField(default=False, verbose_name='Sudah Dibaca')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Dibuat')),
                ('idPelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pelanggan', verbose_name='Pelanggan')),
            ],
            options={
                'verbose_name_plural': 'Notifikasi',
                'db_table': 'notifikasi',
            },
        ),
        migrations.CreateModel(
            name='DiskonPelanggan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('persen_diskon', models.IntegerField(verbose_name='Persen Diskon')),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('tidak_aktif', 'Tidak Aktif')], default='aktif', max_length=50, verbose_name='Status')),
                ('pesan', models.TextField(blank=True, null=True, verbose_name='Pesan')),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Dibuat')),
                ('idPelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pelanggan', verbose_name='Pelanggan')),
                ('idProduk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.produk', verbose_name='Produk')),
            ],
            options={
                'verbose_name_plural': 'Diskon Pelanggan',
                'db_table': 'diskon_pelanggan',
            },
        ),
        migrations.CreateModel(
            name='DetailTransaksi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jumlah_produk', models.IntegerField(verbose_name='Jumlah Produk')),
                ('sub_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sub Total')),
                ('idProduk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produk', verbose_name='Produk')),
                ('idTransaksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.transaksi', verbose_name='Transaksi')),
            ],
            options={
                'verbose_name_plural': 'Detail Transaksi',
                'db_table': 'detail_transaksi',
            },
        ),
    ]
