# Generated by Django 4.2 on 2025-11-20 17:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_transaksi_waktu_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='tanggal',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tanggal Transaksi'),
        ),
    ]
