# Generated by Django 4.2 on 2025-11-21 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_transaksi_tanggal'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelanggan',
            name='birthday_discount_activated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Waktu Diskon Aktif'),
        ),
        migrations.AddField(
            model_name='pelanggan',
            name='is_birthday_discount_active',
            field=models.BooleanField(default=False, verbose_name='Diskon Ultah Aktif'),
        ),
        migrations.AddField(
            model_name='pelanggan',
            name='total_riwayat_belanja',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Total Riwayat Belanja'),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='status_transaksi',
            field=models.CharField(choices=[('DIPROSES', 'Diproses'), ('MENUNGGU VERIFIKASI', 'Menunggu Verifikasi'), ('DIBAYAR', 'Dibayar'), ('DIKIRIM', 'Dikirim'), ('SELESAI', 'Selesai'), ('DIBATALKAN', 'Dibatalkan')], default='DIPROSES', max_length=50, verbose_name='Status Transaksi'),
        ),
    ]
