# Generated by Django 4.2 on 2025-11-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pelanggan_birthday_discount_activated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='last_restock_trigger_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Trigger Restock Broadcast'),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='is_payment_reminder_sent',
            field=models.BooleanField(default=False, verbose_name='Pengingat Pra-Jatuh Tempo Terkirim'),
        ),
    ]
